### ISSUE TITLE
iojs and node 0.12 support

### ISSUE THREAD

**Issue by corbinu** [vdemedes/ronin#9]
On OS X 10.10 both iojs and node 0.12 give this error when running `ronin new hello-world`

```
TypeError: undefined is not a function
    at Program.invoke (/usr/local/lib/node_modules/ronin/build/program.js:302:5)
    at Program.run (/usr/local/lib/node_modules/ronin/build/program.js:180:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/ronin/bin/main.js:10:9)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ronin/bin/ronin:3:1)
```

**Comment by vdemedes** [comment]
Are you sure the commands are properly set up? Because this error means that command does not exist.

**Comment by vdemedes** [comment]
Bug reproduced, working on a fix.

**Comment by corbinu** [comment]
Thanks much!
